[[redirects]]
  from = "/categories"
  to = "/#products"
  status = 301
  force = false

[[redirects]]
  from = "/reviews"
  to = "/#reviews"
  status = 301
  force = false

[[redirects]]
  from = "/tags"
  to = "/#products"
  status = 301
  force = false

[[redirects]]
  from = "/purchase-options"
  to = "/financing"
  status = 301
  force = false

[[redirects]]
  from = "/products"
  to = "/#products"
  status = 301
  force = false

[[redirects]]
  from = "/products/styles"
  to = "/#products"
  status = 301
  force = false

[[redirects]]
  from = "/categories"
  to = "/#products"
  status = 301
  force = false

[[redirects]]
  from = "/categories/playset"
  to = "/playsets"
  status = 301
  force = false
